### ISSUE TITLE
Unable to remove loops

### ISSUE THREAD

**Issue by sagorahmed** [michpohl/Loopy#4]
#### Expected behavior
The users should be able to remove loops from the selected loop's dashboard without getting any trouble.

#### Actual behavior
The removed loops vanished for a while only. But when I restart the app, those loops appears again on the player.

#### How to reproduce
**1.** Open the app.
**2.** Then go to "Browse music library".
**3.** Click on "OPEN SELECTION" after selecting a few songs (You selected songs will be added to the selection dashboard).
**4.** Then try to remove the song/loop by clicking at the cross button at the side of your song on selection dashboard.
**5.** At last, exit and reopen the app and notice that your removed loops are still on the list.

* App version: 0.9
* Operating system: Android 6.0.1

**Comment by michpohl** [comment]
This is an actual error and I can reproduce this. This will be fixed in the near future.

**Comment by sagorahmed** [comment]
Thanks for evaluating it as a real bug. Good to see, you want to fix it. Best of luck!

**Comment by michpohl** [comment]
This should be resolved now with the release of Loopy 2
